# Generated by Django 4.0.3 on 2022-05-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='user_avatar/'),
        ),
    ]
