# Generated by Django 4.0.3 on 2022-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0002_pdfmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodel',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
