# Generated by Django 4.0.3 on 2022-05-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0003_pdfmodel_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodel',
            name='education',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pdfmodel',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pdfmodel',
            name='skills',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
