# Generated by Django 4.0.3 on 2022-05-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0004_pdfmodel_education_pdfmodel_enddate_pdfmodel_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmodel',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pdfmodel',
            name='skills',
            field=models.CharField(max_length=200, null=True, verbose_name='Programming Languages:'),
        ),
    ]
