# Generated by Django 4.0.3 on 2022-05-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0005_alter_pdfmodel_enddate_alter_pdfmodel_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfmodel',
            old_name='info',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='pdfmodel',
            name='work_experience',
            field=models.TextField(null=True),
        ),
    ]
