# Generated by Django 4.0.3 on 2022-05-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0007_rename_name_pdfmodel_fish_remove_pdfmodel_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfmodel',
            old_name='summary',
            new_name='profile',
        ),
    ]
