# Generated by Django 4.0.3 on 2022-05-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0010_pdfmodel_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodel',
            name='millati',
            field=models.CharField(choices=[('uzbek', 'uzbek'), ('rus', 'rus'), ('qozoq', 'qozoq'), ('tojik', 'tojik'), ('boshqa', 'boshqa')], max_length=100, null=True),
        ),
    ]
