# Generated by Django 4.0.3 on 2022-05-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0011_pdfmodel_millati'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodel',
            name='fuqorolik',
            field=models.CharField(choices=[('Uzbekistan', 'Uzbekistan'), ('Russian', 'Russian'), ('Kazak', 'Kazak'), ('Tadjik', 'Tadjik'), ('Boshqa', 'Boshqa')], max_length=100, null=True),
        ),
    ]
