# Generated by Django 4.0.3 on 2022-05-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0012_pdfmodel_fuqorolik'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodel',
            name='ishlamoqchi_info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pdfmodel',
            name='ishlamoqchi_kasb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdfmodel',
            name='oylik',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
