# Generated by Django 4.0.3 on 2022-05-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0013_pdfmodel_ishlamoqchi_info_pdfmodel_ishlamoqchi_kasb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmodel',
            name='ishlamoqchi_info',
            field=models.TextField(null=True),
        ),
    ]
