# Generated by Django 4.0.3 on 2022-05-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0014_alter_pdfmodel_ishlamoqchi_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfmodel',
            name='work_experience',
        ),
        migrations.AlterField(
            model_name='pdfmodel',
            name='oylik',
            field=models.IntegerField(blank=True, null=True, verbose_name='maosh ($)'),
        ),
    ]
