# Generated by Django 4.0.3 on 2022-05-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0016_pdfmodel_prava'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodel',
            name='malumot',
            field=models.CharField(choices=[('Oliy', 'Oliy'), ("O'rta", "O'rta"), ("Maxsus o'rta", "Maxsus o'rta"), ('Magistr', 'Magistr')], max_length=100, null=True),
        ),
    ]
