# Generated by Django 4.0.3 on 2022-05-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0017_pdfmodel_malumot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfmodel',
            name='kasb',
        ),
    ]
